packages:
  - apps/*
  - packages/*
overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1
allowBuilds:
  '@prisma/engines@7.10.0': true
  '@scarf/scarf': false
  esbuild: true
  'prisma@7.10.0': true
minimumReleaseAgeExclude:
  - jose@6.2.12

autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
